// Generated by Wrangler by running `wrangler types`

interface Env {
	PROXYFLARE_WORKERS: "[\"https://proxyflare-1771765050-ofdfhl.guides.workers.dev\",\"https://proxyflare-1771765050-dnfqud.guides.workers.dev\",\"https://proxyflare-1771765050-prjxuc.guides.workers.dev\"]";
}
